# Generated by Django 6.0.4 on 2026-07-03 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetDevice',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=20)),
                ('last_seen_at', models.DateTimeField()),
                ('fps', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('model_version', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['city', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PotholeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'open'), ('in-progress', 'in-progress'), ('resolved', 'resolved')], default='open', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('detected_at', models.DateTimeField()),
                ('city', models.CharField(max_length=120)),
                ('device_id', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('engineer', 'engineer'), ('viewer', 'viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='console_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
