# Generated by Django 6.0.4 on 2026-07-03 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDatasetSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('road_name', models.CharField(max_length=160)),
                ('barangay', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('file_name', models.CharField(blank=True, max_length=180)),
                ('duration_seconds', models.PositiveIntegerField(default=40)),
                ('frame_count', models.PositiveIntegerField(default=879)),
                ('fps', models.DecimalField(decimal_places=2, default=59, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['road_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('dataset', 'dataset'), ('upload', 'upload'), ('live', 'live')], default='dataset', max_length=20)),
                ('uploaded_video', models.FileField(blank=True, upload_to='videos/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('min_confidence', models.PositiveSmallIntegerField(default=85)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('complete', 'complete'), ('failed', 'failed')], default='ready', max_length=20)),
                ('model_version', models.CharField(default='rv-pothole-yolo-lite-1.0', max_length=80)),
                ('frames_processed', models.PositiveIntegerField(default=0)),
                ('inference_fps', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.videodatasetsample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=12)),
                ('road_name', models.CharField(max_length=160)),
                ('timecode_seconds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], max_length=20)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('bbox_x', models.PositiveSmallIntegerField()),
                ('bbox_y', models.PositiveSmallIntegerField()),
                ('bbox_w', models.PositiveSmallIntegerField()),
                ('bbox_h', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='console.videoanalysis')),
            ],
            options={
                'ordering': ['-timecode_seconds', '-confidence'],
            },
        ),
    ]
