# Generated by Django 6.0.4 on 2026-07-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_videodatasetsample_videoanalysis_detectionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='model_version',
            field=models.CharField(default='yolo26-pending', max_length=80),
        ),
    ]
