# Generated by Django 6.0.4 on 2026-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_alter_videoanalysis_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='model_version',
            field=models.CharField(default='opencv-pending', max_length=80),
        ),
    ]
