# Generated by Django 6.0.4 on 2026-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_alter_videoanalysis_model_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='snapshot_image',
            field=models.ImageField(blank=True, upload_to='detections/'),
        ),
    ]
