# Generated by Django 6.0.4 on 2026-07-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_detectionevent_snapshot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('routine', 'routine'), ('scheduled', 'scheduled'), ('urgent', 'urgent'), ('emergency', 'emergency')], max_length=20)),
                ('recommended_action', models.CharField(max_length=180)),
                ('repair_method', models.CharField(max_length=180)),
                ('response_window', models.CharField(max_length=80)),
                ('crew_type', models.CharField(max_length=120)),
                ('detection_count', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('low_count', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_affected_area_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('estimated_material_volume_cum', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('estimated_cost_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_cost_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('engineering_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_recommendation', to='console.videoanalysis')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
