# Generated by Django 6.0.4 on 2026-07-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_engineeringrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='aggregate_quantity_tons',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='asphalt_quantity_tons',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='chainage_station',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='equipment_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='estimated_depth_mm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='estimated_length_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='estimated_width_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='fuel_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='labor_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='lanes_affected',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='pavement_temperature_note',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='photo_after_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='photo_before_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='photo_during_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='road_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='traffic_control_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='traffic_volume_note',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='weather_constraints',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='work_zone_requirements',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
