# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0007_engineeringrecommendation_aggregate_quantity_tons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionevent",
            name="mask_polygon",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="mask_centroid_x",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="mask_centroid_y",
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
