# Generated by Django 6.0.4 on 2026-07-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_detectionevent_mask_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='damage_length_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='damage_perimeter_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='damage_surface_area_sqm',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='damage_width_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='estimated_repair_area_sqm',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='estimated_perimeter_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='engineeringrecommendation',
            name='estimated_repair_area_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
