# Generated by Django 6.0.4 on 2026-07-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_trainingsession_is_active_video_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='source_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='videovisualizeranalysis',
            name='video',
            field=models.FileField(blank=True, upload_to='video_visualizer/uploads/%Y/%m/%d/'),
        ),
    ]
