# Generated by Django 5.0.14 on 2026-07-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_videovisualizeranalysis_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='model_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videopotholetrack',
            name='measurement_basis',
            field=models.CharField(choices=[('visual-estimate', 'visual estimate only'), ('calibrated', 'camera-calibrated estimate'), ('field-measured', 'field measured')], default='visual-estimate', max_length=24),
        ),
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='error_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='legacy_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_analysis', to='console.videoanalysis'),
        ),
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='worker_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='videovisualizeranalysis',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('retrying', 'retrying'), ('complete', 'complete'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='queued', max_length=20),
        ),
    ]
