# Generated by Django 5.0.14 on 2026-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_unify_legacy_analyses'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='frame_detections_artifact',
            field=models.FileField(blank=True, upload_to='video_visualizer/detections/%Y/%m/%d/'),
        ),
    ]
