# Generated by Django 5.0.14 on 2026-07-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0017_remove_missing_legacy_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='calibration_m_per_pixel',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='videovisualizeranalysis',
            name='calibration_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
