# Generated by Django 5.0.14 on 2026-07-15 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_configuration(apps, schema_editor):
    TrainingSession = apps.get_model('console', 'TrainingSession')
    AnalyzerConfiguration = apps.get_model('console', 'AnalyzerConfiguration')
    active_model = TrainingSession.objects.filter(
        status='complete', is_validated=True, is_active_video_model=True
    ).exclude(model_file='').first()
    AnalyzerConfiguration.objects.get_or_create(pk=1, defaults={'model_session': active_model})


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_camera_calibration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('real-time', 'real-time'), ('accurate', 'accurate')], default='accurate', max_length=20)),
                ('confidence_threshold', models.PositiveSmallIntegerField(default=50)),
                ('iou_threshold', models.PositiveSmallIntegerField(default=45)),
                ('device', models.CharField(default='cpu', max_length=60)),
                ('input_resolution', models.PositiveIntegerField(default=640)),
                ('frame_skip', models.PositiveSmallIntegerField(default=1)),
                ('half_precision', models.BooleanField(default=False)),
                ('tracker', models.CharField(default='bytetrack.yaml', max_length=60)),
                ('max_detections', models.PositiveIntegerField(default=100)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('show_labels', models.BooleanField(default=True)),
                ('show_confidence', models.BooleanField(default=True)),
                ('show_tracking_ids', models.BooleanField(default=True)),
                ('show_boxes', models.BooleanField(default=True)),
                ('show_gps_overlay', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.trainingsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_configuration, migrations.RunPython.noop),
    ]
