# Generated by Django 5.0.14 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0019_analyzer_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="augmentation_profile",
            field=models.CharField(default="balanced", max_length=20),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="dataset_manifest",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="freeze_layers",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="optimizer",
            field=models.CharField(default="AdamW", max_length=20),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="seed",
            field=models.PositiveIntegerField(default=42),
        ),
    ]
