# Generated by Django 5.0.14 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0020_training_reproducibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="potholeannotation",
            name="segmentation_points",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
